package com.main

import com.ftn.sbnz.anxietycheck.model.TestTakingUser;
import com.ftn.sbnz.anxietycheck.model.StressCategory.*;
import com.ftn.sbnz.anxietycheck.model.CommonAnxietySymptoms;

import java.time.LocalDate;

rule "Check if user has anxiety based on stress"
	agenda-group "anxiety"
	salience 399 
	when
    	$t: TestTakingUser(stress == StressCategory.HIGH, $symptoms: commonSymptoms, $symptoms.size() > 4,  $startOfSymptoms : start,  $startOfSymptoms.isBefore(LocalDate.now().minusDays(29)), anxious == false)
    	
    then
    	System.out.println("User has anxiety" );  
    	modify($t){
    		setAnxious(true);
    	} 
    	
end


rule "Check if user no longer has anxiety based on stress"
	agenda-group "anxiety"
	salience 399 
	when
		$t : TestTakingUser(stress != StressCategory.HIGH, anxious != false);
	
    then
    	System.out.println("User has no anxiety");  
    	
    	modify($t){
    		setAnxious(false);
    	} 
end

rule "Check if user no longer has anxiety based on stress and time"
	agenda-group "anxiety"
	salience 399 
	when
		$t : TestTakingUser(  anxious != false, stress == StressCategory.HIGH, $startOfSymptoms : start, $startOfSymptoms.isAfter(LocalDate.now().minusDays(29)));
	
    then
    	System.out.println("User has no anxiety");  
    	
    	modify($t){
    		setAnxious(false);
    	} 
    	
end