package com.main

import com.ftn.sbnz.anxietycheck.model.TestTakingUser;
import com.ftn.sbnz.anxietycheck.model.StressCategory.*;
import com.ftn.sbnz.anxietycheck.model.AnxietyDisorder;
import com.ftn.sbnz.anxietycheck.model.Diagnosis;
import com.ftn.sbnz.anxietycheck.model.DepressionSymptoms;


import java.time.LocalDate;

rule "Diagnosis" 
		no-loop
		agenda-group "diagnosis"
		salience -60
    when
        $t: TestTakingUser( $disorder : anxietyDisorder, $disorder != null, $depression : depression)
        $d: Diagnosis($diagnosedDisorder : disorder, $diagnosedDepression : depression, $name : name)
        Boolean(booleanValue == true) from ($disorder == $diagnosedDisorder && $depression == $diagnosedDepression)
    then
    	System.out.println("Diagnosis : " + $d.getTherapy().getName());
    	$t.setDiagnosis($d);
    	$t.setStartOfTherapy(LocalDate.now());
    	update($t);
    	
end

