package com.main

import com.ftn.sbnz.anxietycheck.model.TestTakingUser;
import com.ftn.sbnz.anxietycheck.model.StressCategory;

rule "None stress level"
	salience 100 
    when
        $t: TestTakingUser(  stressPoints/40*100 <= 10, stress == null);
    then
    	System.out.println("Nema stresa" ); 
    	modify($t){
    		setStress(StressCategory.NONE);
    	} 
end
rule "Low stress level"
	salience 405 
    when
        $t: TestTakingUser( stressPoints/40*100 <= 30 && stressPoints/40*100 > 10, stress == null);
    then
    	System.out.println("Niska kolicina stresa" );  
    	modify($t){
    		setStress(StressCategory.LOW);
    	} 
end
rule "Medium stress level"
	salience 405 
    when
        $t: TestTakingUser(  stressPoints/40*100 < 65 && stressPoints/40*100 > 30, stress == null );
    then
    	System.out.println("Srednja kolicina stresa" );  
    	modify($t){
    		setStress(StressCategory.MEDIUM);
    	} 
end
rule "High stress level"
	salience 405 
    when
        $t: TestTakingUser( stressPoints/40*100 >= 65, stress == null );
    then
    	System.out.println("Visoka kolicina stresa" );  
    	modify($t){
    		setStress(StressCategory.HIGH);
    	} 
end
