package com.main

import com.ftn.sbnz.anxietycheck.model.TestTakingUser;
import com.ftn.sbnz.anxietycheck.model.StressCategory;

rule "None stress level"
		agenda-group "stressLevel"
		salience 400 
    when
        $t: TestTakingUser( (stressPoints/40*100 <= 10) , stress != StressCategory.NONE);
    then
    	System.out.println("Nema stresa" ); 
    	modify($t){
    		setStress(StressCategory.NONE);
    	} 
end
rule "Low stress level"
		agenda-group "stressLevel"
		salience 400 
    when
        $t: TestTakingUser(  (stressPoints/40*100 <= 30 &&  stressPoints/40*100 > 10) , stress != StressCategory.LOW);
    then
    	System.out.println("Niska kolicina stresa" );  
    	modify($t){
    		setStress(StressCategory.LOW);
    	} 
end
rule "Medium stress level"
		agenda-group "stressLevel"
		salience 400 
    when
        $t: TestTakingUser(  (stressPoints/40*100 < 65 && stressPoints/40*100 > 30), stress != StressCategory.MEDIUM );
    then
    	System.out.println("Srednja kolicina stresa" );  
    	modify($t){
    		setStress(StressCategory.MEDIUM);
    	} 
end
rule "High stress level"
		agenda-group "stressLevel"
		salience 400 
    when
        $t: TestTakingUser( (stressPoints/40*100 >= 65), stress != StressCategory.HIGH );
    then
    	System.out.println("Visoka kolicina stresa" );  
    	modify($t){
    		setStress(StressCategory.HIGH);
    	} 
end
